# Generated by Django 5.0.4 on 2024-05-01 17:38

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('password', models.CharField(max_length=20)),
                ('username', models.CharField(max_length=20)),
                ('rating', models.FloatField(default=0, max_length=3)),
                ('skills', models.CharField(default='Отсутствуют', max_length=1000)),
            ],
        ),
    ]
